apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - image: IMG
        imagePullPolicy: IfNotPresent
        name: web-ui
        imagePullSecrets:
        - name: docker-registry-secret
        ports:
        - containerPort: 5000
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: web-ui
  sessionAffinity: None
  type: LoadBalancer